### ISSUE TITLE
Investigate why is the app so slow

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1029]
Find out what are the bottlenecks. Propose solutions.

**Comment by kubantjan** [comment]
Sem prosim psat vystupy investigace @krllstdn

**Comment by krllstdn** [comment]
# JA TO JESTE OPRAVIM. HODIL TO SEM ABYCH TO NESTRATIL
## 1. Optimise `get_hla_antibodies_from_recipient_model()`
![image](https://user-images.githubusercontent.com/50211831/196883600-57d04de2-7c64-494a-ab2c-cbf65c116101.png)
On the image is shown the time that takes a function call. As can be seen the function `_from_dict ()` takes too much time to complete. `get_hla_antibodies_from_recipient_model()` is used almost everywhere, so if we optimize it we might significantly increase speed of the whole application.
![image](https://user-images.githubusercontent.com/50211831/196886247-9c2f129a-ac8b-46b2-9c3e-a3f8e9e162c8.png)
On the image above are shown three endpoint calls that are made in calcucate page.
1. http://localhost:8080/v1/txm-event/3/patients/configs/default
2. http://localhost:8080/v1/txm-event/3/configuration/default
3. http://localhost:8080/v1/txm-event/3/matching/calculate-for-config

I decided to code something that will be faster than `_from_dict()` function. And so I did.

The result you can see on the image. All of the endpoints run twice as fast. But some tests are failing. 

## 2. Replace for loops with list comprehension
I still sometimes see in code for loops that could be substituted with list comprehension. So the task is to look for for-loops and to check if it is possible to replace with list comprehension. (For example: _get_txm_event_from_txm_event_model())

## 3. Use sets whenever we need list with unique values.
Set has algorithmic complexity O(1), while lists have O(n), where n is list size. The problem is that sets allow only mutable values, and python objects, that are used in the majority of lists, are immutable. But it can probably be handled with putting an object in a tuple. Or there is some other way. Anyway for me it makes sense to consider it because it can seriously speedup the app.

## 4. ORM
Sqlalchemy might be not as fast as it can be. Investigate it further. Maybe sometimes it makes sense to use clean requests without ORM.`

## 4. cpython
I think probably some parts (such as solver) of txm could be rewritten with cpython (it can run python code faster than python, but if we are to use some specific constructions from cpython it will even faster)

**Comment by kubantjan** [comment]
Next steps:

1) zkontorlovan jestli nevolame veci zbytecne (get_hla_antibodies_from_recipient_model ta vypada ze ji volame treba v http://localhost:8080/v1/txm-event/3/patients/configs/default kde to vypada, ze to k nicemu neni?
2) zkontrolvoat jestli nevolame v endpoitech veci nekolikrat
3) get_hla_antibodies_from_recipient_model vypada ze fakt trva dlouho - udelat issue na jeji zrychleni 
4) sem pridat profil toho kdyz otevru matchings stranku a patients stranku detailni

**Comment by krllstdn** [comment]
Bod 4
Matchings (po optimalizaci)

![Image](https://user-images.githubusercontent.com/50211831/197974736-ef7e0820-01e6-4273-b7fa-8ba50b5733c7.png)

Patients (po optimalizaci)
 

![Image](https://user-images.githubusercontent.com/50211831/197975006-7726f7cc-7150-4131-94ca-6c498f731a73.png)

**Comment by krllstdn** [comment]
@kubantjan chci opravit  bod 1 v bode 1 v me odpovedi. Potrebuju na to vytvorit issue i PR? nebo staci proste pridat do #1046? tam opravy na jeden radek, ale vytvaret issue a PR mi pride zbytecny

**Comment by kubantjan** [comment]
@krllstdn klidně to přidej

**Comment by kubantjan** [comment]
- rozpadenout ty 4 endpointy a shrnout co na nich trva dlouho
- muzes kratky zamysleni jestli se neco nevola zbytecne.

**Comment by krllstdn** [comment]
## Matchings page
![image](https://user-images.githubusercontent.com/50211831/198217796-99a6950e-9f48-4f71-8fec-0b34f4c37222.png)
total time: `3,02s`

## 1. Calculate for config 
By function call in API
### get_txm_event_complete()
![image](https://user-images.githubusercontent.com/50211831/198229378-3df89f61-02a0-4579-832d-da811b0f12b8.png)
- **get_recipient_from_recipient_model()** - by some reason there's called _get_base_patient_from_patient_model() that takes `0,5s`. I don't see the reason why should it be called (all information is already in RecipientModel) - potential`low hanging fruit`
   - query to db takes 0,4s. it might be possible to optimise it, but it is complicated if even possible.
- **_get_txm_event_from_txm_event_model** - takes `1,17s` . there's used for loop. so if we make a list comprehension we can see some performance boost. I tried, it is not so easy to create a comprehension loop, but it might be worth a try.
- **get_hla_typing_from_patient_model()** - two cases of dacite.from_dict() usage. `low-hanging fruit`
### Solver itself. 
Probably it can be optimized. ![image](https://user-images.githubusercontent.com/50211831/198243259-3fdff001-fbb0-4f7f-bab1-ff0719b28ba0.png)






### 2. http://localhost:8080/v1/txm-event/3/patients/configs/default (gets all patients for txm event 3 in `1,32s`) 


### 3. http://localhost:8080/v1/txm-event (gets all txm events)

## Conclusions

**Comment by krllstdn** [comment]
@kubantjan mam hotovo. V conclusions jsou action items, ktery muzou byt udelane dost rychle

**Comment by krllstdn** [comment]
@kubantjan v conclusions jsou action items, ktere muzou byt udelane dost rychle

**Comment by kubantjan** [comment]
get_hla_typing_from_patient_model() vidím tam že píšeš že by šlo zrychlit ale nevidím kolik času to teď trvá

**Comment by krllstdn** [comment]
Opraveno. Trva to 0.475s. Skoro cely ten cas zabira from_dict(), tak ze teoriticky by se dalo optimalizovat a to by mohlo trvat 0.1-0.2 s. Je to dostatecny cas pro optimalizaci nebo na to vykaslame?

**Comment by kubantjan** [comment]
Jop to stojí za to udělaj issue a rovnou na něj mrkni

**Comment by krllstdn** [comment]
# Patients page

Here it is a bit slower due to include-antibodies raw. 

## http://localhost:8080/v1/txm-event/3/patients/configs/default?include-antibodies-raw
this `include-antibodies-raw` makes it slower
- **get_txm_event_complete()**
   - ![image](https://user-images.githubusercontent.com/50211831/198351464-c9e05646-0092-4864-b971-66549295ff7c.png)
- **to_lists_for_fe()**
  -  ![image](https://user-images.githubusercontent.com/50211831/198352099-eda0bed5-c6ee-4e8d-a487-0c83741ec729.png)

Queries take the biggest chunk of its completion time, so probably no easy solutions here.

**Comment by krllstdn** [comment]
### Dacite 
dacite is also used in 
- patient_upload_service.py
- scorer_service.py
- config_service.py.
but it doesn't seem to have any significant impact on speed, so probably it doesn't matter 

 ### GET.v1.txm-event.3.patients.configs.default

- from_dict je porad nekdy v a zere 0.5s
- response_ok probably could be faster, but it is flask's function so probably it can't be optimised by us
![Image](https://user-images.githubusercontent.com/50211831/199115037-45e6a30f-0273-404c-b11c-dcd369ae96f8.png)

**Comment by kubantjan** [comment]
So the conclusion now is that if we want to focus on speedup we shall focus on sql queries. Is that right? @krllstdn ?

**Comment by krllstdn** [comment]
Yes, this is the slowest thing that there is.
