### ISSUE TITLE
Cleanup parsing issue objects

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#621]
1) Txm event id in database in table parsing_issue should be required
2) ParsingIssue is used for two purposes: a temporary object  created when an issue in parsing occurs from which real parsing issue is created higher in the code, when all data is available. This is not good, split it in two objects, one with all fields required, other with just the fields that are required now, that will be used as the temporary object.
3) ParsingIssuePublicDTO is not correct, confirmed_at and confirmed by does not make sense there as it is (check it) used likely only when data are being sent to the app from external sources and in such case the issues are brand new and cannot have any confirmation. Moreover txm_event_name and medical_id should be required

**Comment by kristinagalik** [comment]
@kubantjan this issue is a little outdated, so i have rewritten it ^ pls check issue description if its ok now, or if you have any other suggestions

this is the old version of the description:
The fields medical_id, txm_event_id are currently optional because ParsingInfo is sometimes not provided, which is because of the tests. Improve this.

**Comment by kubantjan** [comment]
@krllstdn we have updated further the desription, let us know whether it is clear now.
